# Auto-generated using compose2nix v0.2.4-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cloudflaretunnel" = {
    image = "cloudflare/cloudflared:latest";
    environmentFiles = [
      "/var/lib/secrets/cf-tunnel.secret"
    ];
    cmd = [ "tunnel" "run" ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-cloudflaretunnel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-cf-tunnel-root.target"
    ];
    wantedBy = [
      "docker-compose-cf-tunnel-root.target"
    ];
  };

  # Auto-update service for Cloudflare Tunnel
  systemd.services.cloudflaretunnel-update = {
    script = ''
      ${pkgs.docker}/bin/docker pull cloudflare/cloudflared:latest
      ${pkgs.systemd}/bin/systemctl restart docker-cloudflaretunnel
    '';
    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
  };

  # Timer to check for updates daily
  systemd.timers.cloudflaretunnel-update = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
      RandomizedDelaySec = "1h";  # Spreads load, updates sometime within an hour of midnight
    };
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-cf-tunnel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
